name: Bug Report 🐞
description: 발견한 버그나 문제를 보고할 때 사용하세요.
title: "[BUG] 제목을 입력하세요"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 버그 보고 안내
        발견한 버그나 문제를 작성해주세요.

  - type: input
    id: bug-summary
    attributes:
      label: 📝 버그 요약
      description: "발생한 버그를 간단히 요약해주세요."
      placeholder: "예: 로그인 시 500 오류 발생"

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 재현 방법
      description: "문제가 발생하는 단계를 순서대로 작성해주세요."
      placeholder: |
        1. 로그인 페이지로 이동합니다.
        2. 사용자 이름과 비밀번호를 입력합니다.
        3. 로그인 버튼을 클릭합니다.
        4. 500 오류 메시지가 표시됩니다.


  - type: textarea
    id: expected-behavior
    attributes:
      label: ✔️ 예상 동작
      description: "정상적으로 동작했을 경우의 기대 결과를 작성해주세요."
      placeholder: "예: 사용자가 대시보드로 이동해야 합니다."


  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 실제 동작
      description: "실제로 발생한 결과를 작성해주세요."
      placeholder: "예: 서버에서 500 내부 서버 오류가 발생합니다."


  - type: textarea
    id: environment
    attributes:
      label: 🌐 환경
      description: "문제가 발생한 환경을 설명해주세요 (운영 체제, 브라우저, 라이브러리 버전 등)."
      placeholder: |
        - 운영 체제: Windows 10
        - 브라우저: Chrome 95
        - 백엔드: Spring Boot 2.5.4
        - 데이터베이스: MySQL 8.0


  - type: textarea
    id: logs
    attributes:
      label: 🐾 관련 로그
      description: "관련된 로그나 에러 메시지가 있으면 추가해주세요."
      placeholder: "로그 메시지를 여기에 붙여넣어 주세요."
      render: shell

  - type: input
    id: additional-context
    attributes:
      label: 📌 참고 사항
      description: "버그와 관련된 추가 정보나 참고할 만한 내용을 작성해주세요."
      placeholder: "예: 다른 페이지에서는 문제가 발생하지 않습니다."